/*import {
  GoalHeadline,
  Subheader,
  Subheaderer,
  Globe,
  TextBlock,
  Image,
  UnknownComponent,
  WideSideBySide,
  Scene,
  SimpleVis,
  ScatterPlot,
  MultipleBarCharts,
  BarChartGDPGrowthWorld,
  DifferenceChartsRegions,
  DifferenceChartsCountries,
  DifferenceChartWorld,
  DifferenceChartSearch,
  WorldTileGrid,
  IllustrationGrid,
  WaterDistribution,
  WaterWithdrawalBySector,
  Carousel,
  FreshwaterAmount,
  FreshwaterPerCapita,
  FreshwaterPerCapita2,
  RegionBeeswarmScroller,
  PovertyLineScroller,
  PovertyLineRegionBeeswarm,
  GiniLinechart,
  GiniExplorerResult,
  GiniBeeswarmExplorer,
  GiniSimulation,
  GiniCovidPlot,
  TourismChart,
  ExcessMortalityTreemap,
  TuberculosisScroller,
  TuberculosisDetection,
  TuberculosisDeaths,
  ExcessChart,
  TemperatureScroller,
  DisasterStackedArea,
  DisasterDamages,
  CountryEmissionProjections,
  ExcessMap,
  VariableWidthBars,
  WaterStress,
  MalnutritionTypes,
  AccessElectricityLineChart,
  ElectricityAccessRegions,
  ElectricityTiersCountries,
  ElectricityTiersEthiopia,
  RenewableStackedBars,
  AirTrafficLines,
  RoadTrafficLines,
  ContainerTraffic,
  VehicleStockLine,
  RegulationMap,
  ICP,
  EVSales,
  BurkinaMap,
  TransportEmissionsScroller,
  RoadTrafficEmissionScatter,
  TransportModeEmissions,
  TernaryPlot,
  Factoid,
  TextEmphasis,
  VisContainer,
  WithdrawalAndPopulation,
  PovertyClimateScroller,
  CovidVax,
  EmissionBars,
  GiniWorld,
  //GenderGapLineChart,
  GenderGapsUnemployment,
  SharedProsperityScatter,
  FoodGroupPrices,
  TopWheatExporters,
  ParallelCoordinatesScroller,
  LearningPlatforms,
  LearningPovertyScenarios,
  LearnLossScroller,
  LearningActivitiesSlopechart,
  LearningActivitiesQuintiles,
  LearningLossesMexico,
  DropOutArrows,
  SaoPauloScoresLines,
  UkraineFoodExportTime,
  UkraineImport,
  UkraineImport2,
  UsedVehiclesChordDiagram,
  UkraineDifferenceChart,
  WaterMap,
  ElectricitySourcesStackedAreas,
  ElectricityAccessEmissionsConnectedScatter,
  LearningActivitiesScroller,
  ElectricitySourcesCountries,
  MalariaScroller,
  MalariaMortality,
  MalariaAgeChart,
  ExportRestrictions,
  ChildhoodImmunizations,
  DptSlope,
  TrafficAccidents,
  ForestMapScroller,
  LakeMead,
  WaterWithdrawalTimeseries,
  NightlightsPopulationScroller,
  ForegoneCare,
  ForestChoropleth,
  TreeCoverLossDriversPie,
  PovertyProjectionLine,
  RedListSlopes,
  TreeCoverLossDriversRegions,
  LakeMeadSatellite,
  MegaDrought,
  SupplyVsUse,
  GHGSectorsTreemap,
  TopIncomeEmissions,
  TimeUseGapChart,
  StackedBarChart,
  MarriageScroller,
  ReadinessVulnerabilityChoro,
  Supplementary,
  AverageExtremeTemperatures,
  OverfishingStackedAreas,
  FishProductionStackedAreasScroller,
  CommitmentsStack,
  KbaLineChart,
  WaterFetchingScroller,
  TiersIllustration,
  GDPScroller,
  FishSectorsStackedAreas,
  VesselsStackedAreas,
  ForestTypesScroller,
  AnimationScroller,
  WildfiresMap,
  FishingAreasMap
  DomesticViolenceCartogram
} from './index.js';

const mapping = {
  text: TextBlock,
  text_emphasis: TextEmphasis,
  headline: GoalHeadline,
  subhed: Subheader,
  subhed2: Subheaderer,
  globe: Globe,
  image: Image,
  wide_scroller: WideSideBySide,
  scroller: WideSideBySide,
  scene: Scene,
  vis: VisContainer,
  supplementary: Supplementary,
  scatter: ScatterPlot,
  demopage_static: PovertyLineRegionBeeswarm,
  simple_vis: SimpleVis,
  multiplebarcharts: MultipleBarCharts,
  barchartgdpgrowthworld: BarChartGDPGrowthWorld,
  differencechartscountries: DifferenceChartsCountries,
  differencechartsregions: DifferenceChartsRegions,
  differencechartworld: DifferenceChartWorld,
  differencechartsearch: DifferenceChartSearch,
  worldtilegrid: WorldTileGrid,
  illustration_grid: IllustrationGrid,
  water_distribution: WaterDistribution,
  water_withdrawal_by_sector: WaterWithdrawalBySector,
  carousel: Carousel,
  freshwater_amount: FreshwaterAmount,
  freshwater_per_capita: FreshwaterPerCapita,
  freshwater_per_capita2: FreshwaterPerCapita2,
  region_beeswarm: RegionBeeswarmScroller,
  interactive_region_beeswarms: PovertyLineRegionBeeswarm,
  factoid: Factoid,
  povertyline_scroller: PovertyLineScroller,
  gini_world: GiniWorld,
  goal10_gini_linechart: GiniLinechart,
  gini_explorer_result: GiniExplorerResult,
  goal10_beeswarm_explorer: GiniBeeswarmExplorer,
  gini_simulation: GiniSimulation,
  gini_covid_plot: GiniCovidPlot,
  tourism_chart: TourismChart,
  excess_mortality_scroller: ExcessMortalityTreemap,
  tuberculosis_scroller: TuberculosisScroller,
  tuberculosis_detection: TuberculosisDetection,
  tuberculosis_deaths: TuberculosisDeaths,
  malaria_scroller: MalariaScroller,
  malaria_mortality: MalariaMortality,
  malaria_deaths_age: MalariaAgeChart,
  childhood_immunizations: ChildhoodImmunizations,
  dpt_slope: DptSlope,
  traffic_accidents: TrafficAccidents,
  foregone_care: ForegoneCare,
  excess_chart: ExcessChart,
  temperature_scroller: TemperatureScroller,
  disaster_stacked_area: DisasterStackedArea,
  disaster_damages: DisasterDamages,
  country_emission_projections: CountryEmissionProjections,
  excess_map: ExcessMap,
  variable_width_bars: VariableWidthBars,
  water_stress: WaterStress,
  malnutrition_types: MalnutritionTypes,
  accesselectricitylinechart: AccessElectricityLineChart,
  electricityaccessregions: ElectricityAccessRegions,
  electricitytierscountries: ElectricityTiersCountries,
  electricitytiersethiopia: ElectricityTiersEthiopia,
  renewablesstackedbars: RenewableStackedBars,
  airtrafficlines: AirTrafficLines,
  roadtrafficlines: RoadTrafficLines,
  containertraffic: ContainerTraffic,
  vehiclestockline: VehicleStockLine,
  regulationmap: RegulationMap,
  icp: ICP,
  covid_vax: CovidVax,
  evsales: EVSales,
  burkinamap: BurkinaMap,
  emissionscroller: TransportEmissionsScroller,
  emissionscatter: RoadTrafficEmissionScatter,
  mode_emissions: TransportModeEmissions,
  ternaryplot: TernaryPlot,
  withdrawal_and_population: WithdrawalAndPopulation,
  povertyclimatescroller: PovertyClimateScroller,
  emissionbars: EmissionBars,
  //unemploymentgender: GenderGapLineChart,
  unemploymentgender: GenderGapsUnemployment,
  sharedprosperity: SharedProsperityScatter,
  food_group_prices: FoodGroupPrices,
  top_wheat_exporters: TopWheatExporters,
  parcoordscroller: ParallelCoordinatesScroller,
  learningplatforms: LearningPlatforms,
  learningpovertyscenarios: LearningPovertyScenarios,
  learnloss: LearnLossScroller,
  learnactivitiesslopechart: LearningActivitiesSlopechart,
  learning_activities_quintiles: LearningActivitiesQuintiles,
  learning_activities_scroller: LearningActivitiesScroller,
  learning_losses_mexico: LearningLossesMexico,
  drop_out_rates: DropOutArrows,
  test_scores_saopaulo: SaoPauloScoresLines,
  ukraine_foodexport_time: UkraineFoodExportTime,
  ukraine_import: UkraineImport,
  ukraine_import2: UkraineImport2,
  used_vehicles: UsedVehiclesChordDiagram,
  differencechartukraine: UkraineDifferenceChart,
  water_map: WaterMap,
  electricitysources: ElectricitySourcesStackedAreas,
  accessemissions: ElectricityAccessEmissionsConnectedScatter,
  electricity_sources_countries: ElectricitySourcesCountries,
  forestmapscroller: ForestMapScroller,
  export_restrictions: ExportRestrictions,
  lake_mead: LakeMead,
  water_withdrawal_timeseries: WaterWithdrawalTimeseries,
  nightlights_population_scroller: NightlightsPopulationScroller,
  forestchoro: ForestChoropleth,
  treecoverloss_drivers_pie: TreeCoverLossDriversPie,
  povertyprojection: PovertyProjectionLine,
  redlistslopes: RedListSlopes,
  drivers_coverloss_pies: TreeCoverLossDriversRegions,
  lake_mead_satellite: LakeMeadSatellite,
  mega_drought: MegaDrought,
  supply_vs_use: SupplyVsUse,
  emissions_sectors: GHGSectorsTreemap,
  top_income_emissions: TopIncomeEmissions,
  gender_time_use: TimeUseGapChart,
  water_fetching: StackedBarChart,
  water_fetching_scroller: WaterFetchingScroller,
  marriage_scroller: MarriageScroller,
  readiness_vulnerability_choro: ReadinessVulnerabilityChoro,
  average_extreme_temperatures: AverageExtremeTemperatures,
  overfished_stocks: OverfishingStackedAreas,
  fish_production: FishProductionStackedAreasScroller,
  commitments_stack: CommitmentsStack,
  kbas_trends: KbaLineChart,
  tiers_illustration: TiersIllustration,
  gdp_scroller: GDPScroller,
  fishing_sectors: FishSectorsStackedAreas,
  vessels: VesselsStackedAreas
};*/

import {
  GoalHeadline,
  Image,
  Subheader,
  Subheaderer,
  WideSideBySide,
  Scene,
  TextBlock,
  UnknownComponent,
  VisContainer,
  ScatterPlot,
  SimpleVis,
  Factoid,
  TextEmphasis,
  Supplementary,
  IllustrationGrid,
  Loading
} from './index.js';

export const mapping = {
  headline: GoalHeadline,
  image: Image,
  subhed: Subheader,
  subhed2: Subheaderer,
  wide_scroller: WideSideBySide,
  scroller: WideSideBySide,
  scene: Scene,
  text: TextBlock,
  visContainer: VisContainer,
  scatter: ScatterPlot,
  simple_vis: SimpleVis,
  factoid: Factoid,
  text_emphasis: TextEmphasis,
  supplementary: Supplementary,
  illustration_grid: IllustrationGrid,
  vis: VisContainer,

  // goal 01
  povertyline_scroller: ['goal01', 'PovertyLineScroller'],
  interactive_region_beeswarms: ['goal01', 'PovertyLineRegionBeeswarm'],
  demopage_static: ['goal01', 'PovertyLineRegionBeeswarm'],
  region_beeswarm: ['goal01', 'RegionBeeswarmScroller'],
  povertyclimatescroller: ['goal01', 'PovertyClimateScroller'],
  emissionbars: ['goal01', 'EmissionBars'],
  povertyprojection: ['goal01', 'PovertyProjectionLine'],

  // goal 02
  malnutrition_types: ['goal02', 'MalnutritionTypes'],
  icp: ['goal02', 'ICP'],
  food_group_prices: ['goal02', 'FoodGroupPrices'],
  top_wheat_exporters: ['goal02', 'TopWheatExporters'],
  ukraine_foodexport_time: ['goal02', 'UkraineFoodExportTime'],
  ukraine_import: ['goal02', 'UkraineImport'],
  ukraine_import2: ['goal02', 'UkraineImport2'],
  export_restrictions: ['goal02', 'ExportRestrictions'],

  // goal 03
  excess_chart: ['goal03', 'ExcessChart'],
  excess_map: ['goal03', 'ExcessMap.'],
  globe: ['goal03', 'Globe'],
  excess_mortality_scroller: ['goal03', 'ExcessMortalityTreemap'],
  covid_vax: ['goal03', 'CovidVax'],
  tuberculosis_detection: ['goal03', 'TuberculosisDetection'],
  tuberculosis_deaths: ['goal03', 'TuberculosisDeaths'],
  tuberculosis_scroller: ['goal03', 'TuberculosisScroller'],
  malaria_scroller: ['goal03', 'MalariaScroller'],
  malaria_mortality: ['goal03', 'MalariaMortality'],
  malaria_deaths_age: ['goal03', 'MalariaAgeChart'],
  childhood_immunizations: ['goal03', 'ChildhoodImmunizations'],
  dpt_slope: ['goal03', 'DptSlope'],
  traffic_accidents: ['goal03', 'TrafficAccidents'],
  foregone_care: ['goal03', 'ForegoneCare'],

  // goal 04
  parcoordscroller: ['goal04', 'ParallelCoordinatesScroller'],
  learningplatforms: ['goal04', 'LearningPlatforms'],
  learningpovertyscenarios: ['goal04', 'LearningPovertyScenarios'],
  learnloss: ['goal04', 'LearnLossScroller'],
  learnactivitiesslopechart: ['goal04', 'LearningActivitiesSlopechart'],
  learning_activities_quintiles: ['goal04', 'LearningActivitiesQuintiles'],
  learning_activities_scroller: ['goal04', 'LearningActivitiesScroller'],
  learning_losses_mexico: ['goal04', 'LearningLossesMexico'],
  drop_out_rates: ['goal04', 'DropOutArrows'],
  test_scores_saopaulo: ['goal04', 'SaoPauloScoresLines'],

  // goal 05
  gender_time_use: ['goal05', 'TimeUseGapChart'],
  water_fetching: ['goal05', 'StackedBarChart'],
  water_fetching_scroller: ['goal05', 'WaterFetchingScroller'],
  marriage_scroller: ['goal05', 'MarriageScroller'],
  domestic_violence: ['goal05', 'DomesticViolenceMap'],
  greening_jobs: ['goal05', 'GreeningJobs'],
  top_performers: ['goal05', 'TopPerformers'],
  tertiary_institutions: ['goal05', 'TertiaryInstitutions'],

  // goal 06
  water_stress: ['goal06', 'WaterStress'],
  water_distribution: ['goal06', 'WaterDistribution'],
  water_withdrawal_by_sector: ['goal06', 'WaterWithdrawalBySector'],
  freshwater_amount: ['goal06', 'FreshwaterAmount'],
  freshwater_per_capita: ['goal06', 'FreshwaterPerCapita'],
  freshwater_per_capita2: ['goal06', 'FreshwaterPerCapita2'],
  withdrawal_and_population: ['goal06', 'WithdrawalAndPopulation'],
  water_map: ['goal06', 'WaterMap'],
  lake_mead: ['goal06', 'LakeMead'],
  water_withdrawal_timeseries: ['goal06', 'WaterWithdrawalTimeseries'],
  lake_mead_satellite: ['goal06', 'LakeMeadSatellite'],
  mega_drought: ['goal06', 'MegaDrought'],
  supply_vs_use: ['goal06', 'SupplyVsUse'],
  precipitation: ['goal06', 'Precipitation'],

  // goal 07
  accesselectricitylinechart: ['goal07', 'AccessElectricityLineChart'],
  electricityaccessregions: ['goal07', 'ElectricityAccessRegions'],
  electricitytierscountries: ['goal07', 'ElectricityTiersCountries'],
  electricitytiersethiopia: ['goal07', 'ElectricityTiersEthiopia'],
  renewablesstackedbars: ['goal07', 'RenewableStackedBars'],
  electricitysources: ['goal07', 'ElectricitySourcesStackedAreas'],
  electricity_sources_countries: ['goal07', 'ElectricitySourcesCountries'],
  ternaryplot: ['goal07', 'TernaryPlot'],
  accessemissions: ['goal07', 'ElectricityAccessEmissionsConnectedScatter'],
  nightlights_population_scroller: ['goal07', 'NightlightsPopulationScroller'],
  tiers_illustration: ['goal07', 'TiersIllustration'],

  // goal 08
  tourism_chart: ['goal08', 'TourismChart'],
  worldtilegrid: ['goal08', 'WorldTileGrid'],
  multiplebarcharts: ['goal08', 'MultipleBarCharts'],
  barchartgdpgrowthworld: ['goal08', 'BarChartGDPGrowthWorld'],
  differencechartsregions: ['goal08', 'DifferenceChartsRegions'],
  differencechartscountries: ['goal08', 'DifferenceChartsCountries'],
  differencechartworld: ['goal08', 'DifferenceChartWorld'],
  differencechartsearch: ['goal08', 'DifferenceChartSearch'],
  //unemploymentgender: ['goal08', 'GenderGapLineChart'],
  unemploymentgender: ['goal08', 'GenderGapsUnemployment'],
  sharedprosperity: ['goal08', 'SharedProsperityScatter'],
  differencechartukraine: ['goal08', 'UkraineDifferenceChart'],

  // goal 09
  airtrafficlines: ['goal09', 'AirTrafficLines'],
  roadtrafficlines: ['goal09', 'RoadTrafficLines'],
  containertraffic: ['goal09', 'ContainerTraffic'],
  vehiclestockline: ['goal09', 'VehicleStockLine'],
  regulationmap: ['goal09', 'RegulationMap'],
  evsales: ['goal09', 'EVSales'],
  burkinamap: ['goal09', 'BurkinaMap'],
  emissionscroller: ['goal09', 'TransportEmissionsScroller'],
  emissionscatter: ['goal09', 'RoadTrafficEmissionScatter'],
  mode_emissions: ['goal09', 'TransportModeEmissions'],
  used_vehicles: ['goal09', 'UsedVehiclesChordDiagram'],
  access_health: ['goal09', 'AccessHealthStackedBars'],
  emissions_sectors_stacked_bars: ['goal09', 'EmissionsSectorsStackedBars'],
  emission_shares_pie: ['goal09', 'EmissionSharesPie'],
  emission_shares_areas: ['goal09', 'EmissionSharesAreas'],
  transport_emissions_areas: ['goal09', 'TransportEmissionsAreas'],
  traffic_lines: ['goal09', 'TrafficLines'],
  travel_time_education: ['goal09', 'TravelTimeEducationBars'],
  airpollution: ['goal09', 'AirPollutionCovid'],

  // goal 10
  gini_world: ['goal10', 'GiniWorld'],
  goal10_gini_linechart: ['goal10', 'GiniLinechart'],
  scene_gini_explorer_result: ['goal10', 'GiniExplorerResult'],
  goal10_beeswarm_explorer: ['goal10', 'GiniBeeswarmExplorer'],
  gini_covid_plot: ['goal10', 'GiniCovidPlot'],

  // goal 11
  waste_scroller: ['goal11', 'WasteScroller'],
  waste_projections: ['goal11', 'WasteProjections'],
  total_waste_projections: ['goal11', 'TotalWasteProjections'],
  percapita_waste_projections: ['goal11', 'PercapitaWasteProjections'],
  waste_composition: ['goal11', 'WasteComposition'],
  waste_collection: ['goal11', 'WasteCollection'],
  waste_management: ['goal11', 'WasteManagement'],
  plastic_scroller: ['goal11', 'PlasticScroller'],
  plastic_trade_scroller: ['goal11', 'PlasticTradeScroller'],
  plastic_waste_flow: ['goal11', 'PlasticWasteFlow'],

  // goal 12
  gdp_scroller: ['goal12', 'GDPScroller'],
  fossil_subsidies: ['goal12', 'FossilSubsidies'],
  sustainability_reports: ['goal12', 'SustainabilityReports'],
  food_loss: ['goal12', 'FoodLoss'],

  // goal 13
  temperature_scroller: ['goal13', 'TemperatureScroller'],
  disaster_multiples: ['goal13', 'ClimateDisasterAreas'],
  disasters: ['goal13', 'ClimateDisastersTotal'],
  disaster_damage_multiples: ['goal13', 'ClimateDisasterDamageAreas'],
  disaster_damage_deaths: ['goal13', 'ClimateDisasterDeaths'],
  ghgases: ['goal13', 'GhgGwpShares'],
  ghg_income_pies: ['goal13', 'GhgIncomePies'],
  country_emission_projections: ['goal13', 'CountryEmissionProjections'],
  variable_width_bars: ['goal13', 'VariableWidthBars'],
  emissions_sectors: ['goal13', 'GHGSectorsTreemap'],
  gas_sectors: ['goal13', 'GHGGasSectorsTreemap'],
  sector_emissions_treemap: ['goal13', 'GhgTreemapScroller'],
  top_income_emissions: ['goal13', 'TopIncomeEmissions'],
  readiness_vulnerability_choro: ['goal13', 'ReadinessVulnerabilityChoro'],
  commitments_stack: ['goal13', 'CommitmentsStack'],
  average_extreme_temperatures: ['goal13', 'AverageExtremeTemperatures'],
  netzero_alluvial: ['goal13', 'NetzeroAlluvial'],
  production_lulucf: ['goal13', 'ProductionLulucfBars'],
  ukraine_impact: ['goal13', 'UkraineImpactLinechart'],

  // goal 14
  overfished_stocks: ['goal14', 'OverfishingStackedAreas'],
  fish_production: ['goal14', 'FishProductionStackedAreasScroller'],
  fishing_sectors: ['goal14', 'FishSectorsPie'],
  vessels: ['goal14', 'VesselsStackedAreas'],
  fishingareasmap: ['goal14', 'FishingAreasMap'],
  kobescroller: ['goal14', 'KobeScroller'],
  endangered_sharks_rays: ['goal14', 'EndangeredSharksRays'],
  oceansscroller: ['goal14', 'OceansScroller'],
  mpascatter: ['goal14', 'MarineProtectedAreasScatter'],
  image: ['goal14', 'Image'],
  bycatch_alluvial: ['goal14', 'BycatchAlluvial'],
  fishinghours_income_maps: ['goal14', 'FishingHoursIncomeMaps'],
  fishinghours_income_scroller: ['goal14', 'FishingHoursIncomeScroller'],

  // goal 15
  treecoverlosscomparator: ['goal15', 'TreeCoverLossComparator'],
  treecoverlosscountries: ['goal15', 'TreeCoverLossCountries'],
  forestmapscroller: ['goal15', 'ForestMapScroller'],
  forestchoro: ['goal15', 'ForestChoropleth'],
  treecoverloss_drivers: ['goal15', 'TreeCoverLossDrivers'],
  treecoverloss_drivers_pie: ['goal15', 'TreeCoverLossDriversPie'],
  drivers_coverloss_pies: ['goal15', 'TreeCoverLossDriversRegions'],
  drivers_coverloss_marimekko: ['goal15', 'TreeCoverLossDriversMarimekko'],
  treecoverlossanimation: ['goal15', 'TreeCoverLossAnimation'],
  redlistslopes: ['goal15', 'RedListSlopes'],
  kbas_trends: ['goal15', 'KbaLineChart'],
  forest_types: ['goal15', 'ForestTypesIllustrations'],
  foresttypesscroller: ['goal15', 'ForestTypesScroller'],
  animationscroller: ['goal15', 'AnimationScroller'],
  wildfiresmap: ['goal15', 'WildfiresMap'],
  illustration: ['goal15', 'Illustration'],

  // goal 16
  homicide_rate_total: ['goal16', 'HomicideRateTotal'],
  homicide_rate: ['goal16', 'HomicideRate'],
  homicide_rate_regional: ['goal16', 'HomicideRateRegional'],
  homicide_rate_victims: ['goal16', 'HomicideRateVictims'],
  homicides_by_sex_over_time: ['goal16', 'HomicidesBySexOverTime'],
  homicides_by_sex_and_country: ['goal16', 'HomicidesBySexAndCountry'],
  persons_arrested_suspected: ['goal16', 'PersonsArrestedSuspected'],
  causes_of_death: ['goal16', 'CausesOfDeath'],
  crime_vs_conflict: ['goal16', 'CrimeVsConflict'],
  events_and_fatalities_map: ['goal16', 'EventsAndFatalitiesMap'],
  people_in_fragile_conflict: ['goal16', 'PeopleInFragileConflict'],
  poor_vs_fcs: ['goal16', 'PoorVsFCS'],
  food_insecurity_fcs: ['goal16', 'FoodInsecurityFCS'],
  ukraine_fatalities: ['goal16', 'UkraineFatalities'],
  ukraine_refugees: ['goal16', 'UkraineRefugees'],
  ukraine_gdp_growth: ['goal16', 'UkraineGDPGrowth'],
  yemen: ['goal16', 'Yemen'],

  // goal 17
  oda_growth: ['goal17', 'ODAGrowth'],
  oda_gni_share: ['goal17', 'ODAGNIShare'],
  oda_gni_ldc: ['goal17', 'ODAGNILDC'],
  oda_gni_absolute: ['goal17', 'ODAGNIAbsolute'],
  oda_flows: ['goal17', 'ODAFlows'],
  sector_vis: ['goal17', 'SectorVis'],
  oda_climate_change: ['goal17', 'ODAClimateChange'],
  oda_refugee: ['goal17', 'ODARefugee'],
  oda_flow: ['goal17', 'ODAFlow']
};

export default (contentType, inView = true) => {
  if (inView) {
    if (mapping.hasOwnProperty(contentType)) {
      return mapping[contentType];
    }

    return UnknownComponent;
  }

  return Loading;
};
